/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'kent' at '7/25/14 10:58 AM' with Gradle 2.0
 *
 * @author kent, @date 7/25/14 10:58 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
