/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'kent' at '7/25/14 10:58 AM' with Gradle 2.0
 *
 * @author kent, @date 7/25/14 10:58 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
